# Generated by Django 2.0.3 on 2018-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('card_image_sequence', models.ManyToManyField(to='images.Image')),
            ],
        ),
    ]
