# Generated by Django 2.0.3 on 2018-04-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='card_image_sequence',
            field=models.ManyToManyField(blank=True, null=True, to='images.Image'),
        ),
    ]
