# Generated by Django 2.0.3 on 2018-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180426_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='card_image_sequence',
        ),
        migrations.AddField(
            model_name='game',
            name='opencard1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='opencard2',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
