# Generated by Django 2.0.3 on 2018-05-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180511_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mode',
        ),
    ]
