# Generated by Django 2.0.3 on 2018-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='joinid',
            field=models.IntegerField(default=17400),
        ),
    ]
