# Generated by Django 2.0.3 on 2018-05-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180526_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='p2_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
