# Generated by Django 2.0.3 on 2018-12-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180526_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='p1_online',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p2_online',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_score',
        ),
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player_scores',
            field=models.CharField(default='[0]', max_length=255),
        ),
    ]
