# Generated by Django 2.0.3 on 2018-12-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20181229_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
